name: Generate README.md

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  generate-readme:
    name: Generate README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - uses: diamondburned/cache-install@main
        with:
          shell-file: shell.nix

      - run: ./README-generate README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md
          commit_author: GitHub <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ${{ github.ref_name }}
