name: Health check

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  health-check:
    name: Health check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: ./health-check >> health-data.csv
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run periodic health check
