name: Health check

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health-check:
    name: Health check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - run: ./health-check >> health-data.csv

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run periodic health check
          commit_author: GitHub <41898282+github-actions[bot]@users.noreply.github.com>

  generate-readme:
    uses: ./.github/workflows/generate-readme.yml
    needs: health-check
    secrets: inherit
